name: loja_virtual
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
#  font_awesome_flutter : ^7.1.0
  flutter_staggered_grid_view: ^0.3.0
  cloud_firestore: ^0.12.9
  firebase_analytics: 1.0.2
  firebase_messaging: 1.0.4
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  path_provider: ^0.4.1
  firebase_auth: ^0.11.1+12
  url_launcher: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true